# Generated by Django 5.2.1 on 2025-06-03 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spog_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('work_email', models.EmailField(max_length=254)),
                ('mobile_dialing_code', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=20)),
                ('mobile_country_code', models.CharField(max_length=10)),
                ('zuid', models.CharField(max_length=100)),
                ('access_level_id', models.CharField(max_length=100)),
                ('invite_status', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('photo_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='spog_dashboard.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='spog_dashboard.employee')),
            ],
        ),
    ]
