# Generated by Django 5.2.1 on 2025-06-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spog_dashboard', '0003_remove_employee_employee_id_remove_position_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeShift',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('schedule', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('break_duration', models.CharField(blank=True, max_length=20, null=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('pay', models.CharField(blank=True, max_length=20, null=True)),
                ('rate', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
