# Generated by Django 5.2.1 on 2025-06-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spog_dashboard', '0005_alter_employee_id_alter_position_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutotaskTicketStatus',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
