# Generated by Django 5.2.1 on 2025-06-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spog_dashboard', '0006_autotaskticketstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotaskticketstatus',
            name='ticketNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
