# Generated by Django 5.2.1 on 2025-07-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spog_dashboard', '0008_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('client_name', models.TextField()),
                ('client_type', models.TextField(blank=True, null=True)),
                ('parent_company_name', models.TextField(blank=True, null=True)),
                ('territory', models.TextField(blank=True, null=True)),
                ('address_1', models.TextField(blank=True, null=True)),
                ('address_2', models.TextField(blank=True, null=True)),
                ('country_name', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('postal_zip', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('company_number', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'spog_dashboard_clients',
            },
        ),
    ]
