"""
Django settings for spog_centralize_softwarev project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y65hftg7-gu89ihw9kqbp$*ogq*wgj8m0k9@yto24gzb!yr_*5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'spog_dashboard'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Authentication
ROOT_URLCONF = 'spog_centralize_softwarev.urls'  # Replace with your project name
WSGI_APPLICATION = 'spog_centralize_softwarev.wsgi.application'
LOGIN_REDIRECT_URL = '/admin_dashboard/'
LOGOUT_REDIRECT_URL = 'admin_dashboard'
#LOGIN_REDIRECT_URL = '/user-dashboard/'
#LOGOUT_REDIRECT_URL = 'user-dashboard'
# LOGIN_URL = '/accounts/login/'
# LOGOUT_REDIRECT_URL = '/accounts/login/'
# LOGIN_REDIRECT_URL = '/user-dashboard/'  # After successful login
# LOGIN_URL = '/accounts/login/'


# Session Security
SESSION_COOKIE_AGE = 3600  # 1 hour
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #'DIRS': [],
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'spog_centralize_softwarev.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#DATABASES = {
     #'default': {
      #   'ENGINE': 'django.db.backends.sqlite3',
       #  'NAME': BASE_DIR / 'db.sqlite3',
    #}
 #}
DATABASES = {
  'default': {
  'ENGINE': 'django.db.backends.postgresql',
  'NAME': 'dev_spog_rds',         # Database name
  'USER': 'postgres',       # PostgreSQL username
  'PASSWORD': 'MKQX**H4C-k0yMN>#x3bxGk.1Psm', # PostgreSQL password
  'HOST': 'dev-spog-postgresql.co5uwimya0ca.us-east-1.rds.amazonaws.com',       # Use '127.0.0.1' if needed
  'PORT': '5432',            # Default PostgreSQL port
    }
}
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
DATABASES = {
  'default': {
  'ENGINE': 'django.db.backends.postgresql',
  'NAME': 'dev_spog_rds',         # Database name
  'USER': 'postgres',       # PostgreSQL username
  'PASSWORD': 'MKQX**H4C-k0yMN>#x3bxGk.1Psm', # PostgreSQL password
  'HOST': 'dev-spog-postgresql.co5uwimya0ca.us-east-1.rds.amazonaws.com',       # Use '127.0.0.1' if needed
  'PORT': '5432',            # Default PostgreSQL port
    }
}
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


